'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="DTAM_TIHI")>  _
Partial Public Class Linq_SET_PAGEDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertSET_PAGE_SUB_MAIN(instance As SET_PAGE_SUB_MAIN)
    End Sub
  Partial Private Sub UpdateSET_PAGE_SUB_MAIN(instance As SET_PAGE_SUB_MAIN)
    End Sub
  Partial Private Sub DeleteSET_PAGE_SUB_MAIN(instance As SET_PAGE_SUB_MAIN)
    End Sub
  Partial Private Sub InsertSET_PAGE_MAIN(instance As SET_PAGE_MAIN)
    End Sub
  Partial Private Sub UpdateSET_PAGE_MAIN(instance As SET_PAGE_MAIN)
    End Sub
  Partial Private Sub DeleteSET_PAGE_MAIN(instance As SET_PAGE_MAIN)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("DTAM_TIHIConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property SET_PAGE_SUB_MAINs() As System.Data.Linq.Table(Of SET_PAGE_SUB_MAIN)
		Get
			Return Me.GetTable(Of SET_PAGE_SUB_MAIN)
		End Get
	End Property
	
	Public ReadOnly Property SET_PAGE_MAINs() As System.Data.Linq.Table(Of SET_PAGE_MAIN)
		Get
			Return Me.GetTable(Of SET_PAGE_MAIN)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.SET_PAGE_SUB_MAIN")>  _
Partial Public Class SET_PAGE_SUB_MAIN
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IDA As Integer
	
	Private _RID As System.Nullable(Of Integer)
	
	Private _FK_PAGE_MAIN As System.Nullable(Of Integer)
	
	Private _TYPE_PEOPLE As System.Nullable(Of Integer)
	
	Private _PROCESS_WEIGHT As System.Nullable(Of Integer)
	
	Private _PAGE_ID As System.Nullable(Of Integer)
	
	Private _PAGE_TYPE As System.Nullable(Of Integer)
	
	Private _PAGE_NAME As String
	
	Private _PAGE_PATH As String
	
	Private _ICON_PATH As String
	
	Private _ACTIVEFACT As System.Nullable(Of Integer)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDAChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDAChanged()
    End Sub
    Partial Private Sub OnRIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnRIDChanged()
    End Sub
    Partial Private Sub OnFK_PAGE_MAINChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnFK_PAGE_MAINChanged()
    End Sub
    Partial Private Sub OnTYPE_PEOPLEChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnTYPE_PEOPLEChanged()
    End Sub
    Partial Private Sub OnPROCESS_WEIGHTChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnPROCESS_WEIGHTChanged()
    End Sub
    Partial Private Sub OnPAGE_IDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnPAGE_IDChanged()
    End Sub
    Partial Private Sub OnPAGE_TYPEChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnPAGE_TYPEChanged()
    End Sub
    Partial Private Sub OnPAGE_NAMEChanging(value As String)
    End Sub
    Partial Private Sub OnPAGE_NAMEChanged()
    End Sub
    Partial Private Sub OnPAGE_PATHChanging(value As String)
    End Sub
    Partial Private Sub OnPAGE_PATHChanged()
    End Sub
    Partial Private Sub OnICON_PATHChanging(value As String)
    End Sub
    Partial Private Sub OnICON_PATHChanged()
    End Sub
    Partial Private Sub OnACTIVEFACTChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnACTIVEFACTChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDA", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IDA() As Integer
		Get
			Return Me._IDA
		End Get
		Set
			If ((Me._IDA = value)  _
						= false) Then
				Me.OnIDAChanging(value)
				Me.SendPropertyChanging
				Me._IDA = value
				Me.SendPropertyChanged("IDA")
				Me.OnIDAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RID", DbType:="Int")>  _
	Public Property RID() As System.Nullable(Of Integer)
		Get
			Return Me._RID
		End Get
		Set
			If (Me._RID.Equals(value) = false) Then
				Me.OnRIDChanging(value)
				Me.SendPropertyChanging
				Me._RID = value
				Me.SendPropertyChanged("RID")
				Me.OnRIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FK_PAGE_MAIN", DbType:="Int")>  _
	Public Property FK_PAGE_MAIN() As System.Nullable(Of Integer)
		Get
			Return Me._FK_PAGE_MAIN
		End Get
		Set
			If (Me._FK_PAGE_MAIN.Equals(value) = false) Then
				Me.OnFK_PAGE_MAINChanging(value)
				Me.SendPropertyChanging
				Me._FK_PAGE_MAIN = value
				Me.SendPropertyChanged("FK_PAGE_MAIN")
				Me.OnFK_PAGE_MAINChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TYPE_PEOPLE", DbType:="Int")>  _
	Public Property TYPE_PEOPLE() As System.Nullable(Of Integer)
		Get
			Return Me._TYPE_PEOPLE
		End Get
		Set
			If (Me._TYPE_PEOPLE.Equals(value) = false) Then
				Me.OnTYPE_PEOPLEChanging(value)
				Me.SendPropertyChanging
				Me._TYPE_PEOPLE = value
				Me.SendPropertyChanged("TYPE_PEOPLE")
				Me.OnTYPE_PEOPLEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PROCESS_WEIGHT", DbType:="Int")>  _
	Public Property PROCESS_WEIGHT() As System.Nullable(Of Integer)
		Get
			Return Me._PROCESS_WEIGHT
		End Get
		Set
			If (Me._PROCESS_WEIGHT.Equals(value) = false) Then
				Me.OnPROCESS_WEIGHTChanging(value)
				Me.SendPropertyChanging
				Me._PROCESS_WEIGHT = value
				Me.SendPropertyChanged("PROCESS_WEIGHT")
				Me.OnPROCESS_WEIGHTChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PAGE_ID", DbType:="Int")>  _
	Public Property PAGE_ID() As System.Nullable(Of Integer)
		Get
			Return Me._PAGE_ID
		End Get
		Set
			If (Me._PAGE_ID.Equals(value) = false) Then
				Me.OnPAGE_IDChanging(value)
				Me.SendPropertyChanging
				Me._PAGE_ID = value
				Me.SendPropertyChanged("PAGE_ID")
				Me.OnPAGE_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PAGE_TYPE", DbType:="Int")>  _
	Public Property PAGE_TYPE() As System.Nullable(Of Integer)
		Get
			Return Me._PAGE_TYPE
		End Get
		Set
			If (Me._PAGE_TYPE.Equals(value) = false) Then
				Me.OnPAGE_TYPEChanging(value)
				Me.SendPropertyChanging
				Me._PAGE_TYPE = value
				Me.SendPropertyChanged("PAGE_TYPE")
				Me.OnPAGE_TYPEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PAGE_NAME", DbType:="NVarChar(MAX)")>  _
	Public Property PAGE_NAME() As String
		Get
			Return Me._PAGE_NAME
		End Get
		Set
			If (String.Equals(Me._PAGE_NAME, value) = false) Then
				Me.OnPAGE_NAMEChanging(value)
				Me.SendPropertyChanging
				Me._PAGE_NAME = value
				Me.SendPropertyChanged("PAGE_NAME")
				Me.OnPAGE_NAMEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PAGE_PATH", DbType:="NVarChar(MAX)")>  _
	Public Property PAGE_PATH() As String
		Get
			Return Me._PAGE_PATH
		End Get
		Set
			If (String.Equals(Me._PAGE_PATH, value) = false) Then
				Me.OnPAGE_PATHChanging(value)
				Me.SendPropertyChanging
				Me._PAGE_PATH = value
				Me.SendPropertyChanged("PAGE_PATH")
				Me.OnPAGE_PATHChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ICON_PATH", DbType:="NVarChar(MAX)")>  _
	Public Property ICON_PATH() As String
		Get
			Return Me._ICON_PATH
		End Get
		Set
			If (String.Equals(Me._ICON_PATH, value) = false) Then
				Me.OnICON_PATHChanging(value)
				Me.SendPropertyChanging
				Me._ICON_PATH = value
				Me.SendPropertyChanged("ICON_PATH")
				Me.OnICON_PATHChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ACTIVEFACT", DbType:="Int")>  _
	Public Property ACTIVEFACT() As System.Nullable(Of Integer)
		Get
			Return Me._ACTIVEFACT
		End Get
		Set
			If (Me._ACTIVEFACT.Equals(value) = false) Then
				Me.OnACTIVEFACTChanging(value)
				Me.SendPropertyChanging
				Me._ACTIVEFACT = value
				Me.SendPropertyChanged("ACTIVEFACT")
				Me.OnACTIVEFACTChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.SET_PAGE_MAIN")>  _
Partial Public Class SET_PAGE_MAIN
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IDA As Integer
	
	Private _RID As System.Nullable(Of Integer)
	
	Private _TYPE_PEOPLE As System.Nullable(Of Integer)
	
	Private _PROCESS_WEIGHT As System.Nullable(Of Integer)
	
	Private _PAGE_ID As System.Nullable(Of Integer)
	
	Private _PAGE_NAME As String
	
	Private _PAGE_PATH As String
	
	Private _ICON_PATH As String
	
	Private _ACTIVEFACT As System.Nullable(Of Integer)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDAChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDAChanged()
    End Sub
    Partial Private Sub OnRIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnRIDChanged()
    End Sub
    Partial Private Sub OnTYPE_PEOPLEChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnTYPE_PEOPLEChanged()
    End Sub
    Partial Private Sub OnPROCESS_WEIGHTChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnPROCESS_WEIGHTChanged()
    End Sub
    Partial Private Sub OnPAGE_IDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnPAGE_IDChanged()
    End Sub
    Partial Private Sub OnPAGE_NAMEChanging(value As String)
    End Sub
    Partial Private Sub OnPAGE_NAMEChanged()
    End Sub
    Partial Private Sub OnPAGE_PATHChanging(value As String)
    End Sub
    Partial Private Sub OnPAGE_PATHChanged()
    End Sub
    Partial Private Sub OnICON_PATHChanging(value As String)
    End Sub
    Partial Private Sub OnICON_PATHChanged()
    End Sub
    Partial Private Sub OnACTIVEFACTChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnACTIVEFACTChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDA", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IDA() As Integer
		Get
			Return Me._IDA
		End Get
		Set
			If ((Me._IDA = value)  _
						= false) Then
				Me.OnIDAChanging(value)
				Me.SendPropertyChanging
				Me._IDA = value
				Me.SendPropertyChanged("IDA")
				Me.OnIDAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RID", DbType:="Int")>  _
	Public Property RID() As System.Nullable(Of Integer)
		Get
			Return Me._RID
		End Get
		Set
			If (Me._RID.Equals(value) = false) Then
				Me.OnRIDChanging(value)
				Me.SendPropertyChanging
				Me._RID = value
				Me.SendPropertyChanged("RID")
				Me.OnRIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TYPE_PEOPLE", DbType:="Int")>  _
	Public Property TYPE_PEOPLE() As System.Nullable(Of Integer)
		Get
			Return Me._TYPE_PEOPLE
		End Get
		Set
			If (Me._TYPE_PEOPLE.Equals(value) = false) Then
				Me.OnTYPE_PEOPLEChanging(value)
				Me.SendPropertyChanging
				Me._TYPE_PEOPLE = value
				Me.SendPropertyChanged("TYPE_PEOPLE")
				Me.OnTYPE_PEOPLEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PROCESS_WEIGHT", DbType:="Int")>  _
	Public Property PROCESS_WEIGHT() As System.Nullable(Of Integer)
		Get
			Return Me._PROCESS_WEIGHT
		End Get
		Set
			If (Me._PROCESS_WEIGHT.Equals(value) = false) Then
				Me.OnPROCESS_WEIGHTChanging(value)
				Me.SendPropertyChanging
				Me._PROCESS_WEIGHT = value
				Me.SendPropertyChanged("PROCESS_WEIGHT")
				Me.OnPROCESS_WEIGHTChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PAGE_ID", DbType:="Int")>  _
	Public Property PAGE_ID() As System.Nullable(Of Integer)
		Get
			Return Me._PAGE_ID
		End Get
		Set
			If (Me._PAGE_ID.Equals(value) = false) Then
				Me.OnPAGE_IDChanging(value)
				Me.SendPropertyChanging
				Me._PAGE_ID = value
				Me.SendPropertyChanged("PAGE_ID")
				Me.OnPAGE_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PAGE_NAME", DbType:="NVarChar(MAX)")>  _
	Public Property PAGE_NAME() As String
		Get
			Return Me._PAGE_NAME
		End Get
		Set
			If (String.Equals(Me._PAGE_NAME, value) = false) Then
				Me.OnPAGE_NAMEChanging(value)
				Me.SendPropertyChanging
				Me._PAGE_NAME = value
				Me.SendPropertyChanged("PAGE_NAME")
				Me.OnPAGE_NAMEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PAGE_PATH", DbType:="NVarChar(MAX)")>  _
	Public Property PAGE_PATH() As String
		Get
			Return Me._PAGE_PATH
		End Get
		Set
			If (String.Equals(Me._PAGE_PATH, value) = false) Then
				Me.OnPAGE_PATHChanging(value)
				Me.SendPropertyChanging
				Me._PAGE_PATH = value
				Me.SendPropertyChanged("PAGE_PATH")
				Me.OnPAGE_PATHChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ICON_PATH", DbType:="NVarChar(MAX)")>  _
	Public Property ICON_PATH() As String
		Get
			Return Me._ICON_PATH
		End Get
		Set
			If (String.Equals(Me._ICON_PATH, value) = false) Then
				Me.OnICON_PATHChanging(value)
				Me.SendPropertyChanging
				Me._ICON_PATH = value
				Me.SendPropertyChanged("ICON_PATH")
				Me.OnICON_PATHChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ACTIVEFACT", DbType:="Int")>  _
	Public Property ACTIVEFACT() As System.Nullable(Of Integer)
		Get
			Return Me._ACTIVEFACT
		End Get
		Set
			If (Me._ACTIVEFACT.Equals(value) = false) Then
				Me.OnACTIVEFACTChanging(value)
				Me.SendPropertyChanging
				Me._ACTIVEFACT = value
				Me.SendPropertyChanged("ACTIVEFACT")
				Me.OnACTIVEFACTChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
