<?xml version="1.0" encoding="utf-8"?><Database Name="DTAM_TIHI_MEDICAL_RECORDS" Class="Linq_MEDICAL_RECORDDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.0.2.3;Initial Catalog=DTAM_TIHI_MEDICAL_RECORDS;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DTAM_TIHI_MEDICAL_RECORDSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MEDICAL_RECORDS_VALIDATE" Member="MEDICAL_RECORDS_VALIDATEs">
    <Type Name="MEDICAL_RECORDS_VALIDATE">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_IDA_INFOR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TREATMENT_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LICENSE_NUMBER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PAYMENT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PAYMENT_DES" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PAYMENT_NAME" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PAYMENT_NAME_DES" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="COMPLETE_DOC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DATE_ISSUE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EXPIRE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HOSPITAL_MAIN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HOSPITAL_MAIN_DES" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HOSPITAL_RESERVE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HOSPITAL_RESERVE_DES" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MAX_AMOUNT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AMOUNT_SPENT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DESCRIPTION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NOT_ACTIVE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VALIDATE_MAIN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VALIDATE_SECONDARY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CREATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATE_USER" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="UPDATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPDATE_USER" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ACTIVEFACT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GUID_CREATE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GUID_UPDATE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="USER_SERVICEUNIT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="USER_INVENTORY" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MEDICAL_RECORDS_INFORMATION" Member="MEDICAL_RECORDS_INFORMATIONs">
    <Type Name="MEDICAL_RECORDS_INFORMATION">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TITLE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FIRST_NAME" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="LAST_NAME" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="IDENTIFICATION_CARD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FULLNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TYPE_PATIENT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TYPE_HOSPTIAL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ALIEN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PASSPORT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VIP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VIP_CATEGORY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDENTIFICATION_EXPIRED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IDENTIFICATION_OUT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SEX" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TWINS" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PATIENT_GROUP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="COUNT_DOC_PATIENT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BIRTHDAY" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BIRTHDAY_THAI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BLOOD_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUSOFLIFE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DIE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ELEMENTAL_MAIN" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ELEMENTAL_MINOR" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="NATIONNALITY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RACE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RELIGION" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CAREER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="COMMUNITY_STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TEL_PATIENT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EMAIL_PATIENT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EDUCATION" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WORKPLACE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DUTY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RESERVE_NAME" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="RESERVE_TEL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RESERVE_RERATIONSHIP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RESERVE_ADDRESS" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ADDRESS_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ADDRESS_TYPE_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HOUSE_NO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SOI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MOO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="STREET" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DISTRICT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DISTRICT_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AMPHUR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AMPHUR_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PROVINCE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PROVINCE_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="COUNTY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="COUNTY_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ADDRESS_STYLE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ADDRESS_STYLE_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ZIPCODE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TEL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PHONE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CONTACT_ADDRESS_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CONTACT_HOUSE_NO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CONTACT_SOI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CONTACT_MOO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CONTACT_STREET" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CONTACT_DISTRICT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CONTACT_DISTRICT_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CONTACT_AMPHUR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CONTACT_AMPHUR_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CONTACT_PROVINCE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CONTACT_PROVINCE_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CONTACT_COUNTY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CONTACT_COUNTY_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CONTACT_ADDRESS_STYLE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CONTACT_ZIPCODE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CONTACT_TEL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CONTACT_PHONE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CONTACT_MAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STATUS_ADDRESS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MARRY_STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MARRY_TITLE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MARRY_FIRST_NAME" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MARRY_LAST_NAME" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MARRY_CAREER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MARRY_IDENTIFICATION_CARD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MARRY_NATIONALITY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FATHER_TITLE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FATHER_FIRST_NAME" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="FATHER_LAST_NAME" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="FATHER_CAREER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FATHER_IDENTIFICATION_CARD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FATHER_NATIONALITY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MATHER_TITLE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MATHER_FIRST_NAME" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MATHER_LAST_NAME" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MATHER_CAREER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MATHER_IDENTIFICATION_CARD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MATHER_NATIONALITY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OTHER_TITLE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OTHER_FIRST_NAME" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="OTHER_LAST_NAME" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="OTHER_CAREER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OTHER_IDENTIFICATION_CARD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OTHER_NATIONALITY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OTHER_PHONEHOME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="OTHER_PHONE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="WARNING_MESSAGE" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CREATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATE_USER" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="UPDATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPDATE_USER" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="FATHER_CONGENITIAL_DISORDER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MOTHER_CONGENITIAL_DISORDER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="OTHER_RELATIONSHIP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ACTIVEFACT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DOCUMENT_NUMBER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="OFFCIAL_NUMBER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PATH_FILE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HNYEAR" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HNNUMBER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MINUTE_BIRTH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HOUR_BIRTH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FIRST_NAME_EN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LAST_NAME_EN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AGE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GUID_CREATE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GUID_UPDATE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="USER_SERVICEUNIT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="USER_INVENTORY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CONGENITALDISEASE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CONGENITALDISEASE_DETAIL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>